"""
Django settings for MSc_Research_Django project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys
from configparser import RawConfigParser


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*so-zc0w&wc=@&n1bdv((x*j1zfh4=yxh=v5u2_2*8qm=qp=u4'

# SECURITY WARNING: don't run with debug turned on in production!
# if 'runserver' in sys.argv:
#     DEBUG = True
# else:
#     DEBUG = False

DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'providers_app.apps.ProvidersAppConfig',
    'developers_app.apps.DevelopersAppConfig',
    'controller_app.apps.ControllerAppConfig',
    'profiles.apps.ProfilesConfig',
    'bootstrap4',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MSc_Research_Django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MSc_Research_Django.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# Dev mode:
if 'runserver' in sys.argv:
    DB_HOST = 'localhost'
    RMQ_HOST = 'localhost'
    DEBUG = True
# Production mode
else:
    RMQ_HOST = 'rabbitmq'
    DB_HOST = 'db'

RMQ_PORT = '5672'
RMQ_MNG_PORT = '15672'
DB_PORT = '5432'
PATH = r'./settings.ini'

print(PATH)

config = RawConfigParser()
config.read(PATH)

POSTGRES_USER = config.get('postgres', 'POSTGRES_USER')
POSTGRES_PASS = config.get('postgres', 'POSTGRES_PASS')

# RabbitMQ configurations
RABBITMQ_HOST = RMQ_HOST
RABBITMQ_PORT = RMQ_PORT
RABBITMQ_MANAGEMENT_PORT = RMQ_MNG_PORT
RABBITMQ_USER = config.get('rabbitmq', 'RABBITMQ_USER')
RABBITMQ_PASS = config.get('rabbitmq', 'RABBITMQ_PASS')

# Fabric config
CONTROLLER_TOKEN = config.get('fabric', 'CONTROLLER_TOKEN')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'myproject',
        'USER': POSTGRES_USER,
        'PASSWORD': POSTGRES_PASS,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Toronto'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
if DEBUG:
    STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static/'),)
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

LOGIN_URL = '/profiles/user_login'


