# Generated by Django 2.2.6 on 2019-12-23 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers_app', '0001_initial'),
        ('profiles', '0002_provider_last_ready_signal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Provider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers_app.Services')),
            ],
        ),
    ]
