# Generated by Django 2.2.10 on 2020-05-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='corr_id',
            field=models.UUIDField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='response',
            field=models.TextField(default=''),
        ),
    ]
