# Generated by Django 2.2.6 on 2019-12-23 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_provider_last_ready_signal'),
        ('developers_app', '0001_initial'),
        ('providers_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
