# Generated by Django 2.2.6 on 2019-12-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers_app', '0002_auto_20191223_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='developer',
            new_name='provider',
        ),
        migrations.AddField(
            model_name='job',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
