# Generated by Django 2.2.6 on 2019-12-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers_app', '0003_auto_20191223_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
