# Generated by Django 2.2.6 on 2020-01-06 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers_app', '0004_auto_20191223_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ack_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 1, 0, 0)),
        ),
    ]
