# Generated by Django 2.2.6 on 2020-01-06 22:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('providers_app', '0005_auto_20200106_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='ack_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 1, 5, 18, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 1, 5, 18, tzinfo=utc)),
        ),
    ]
