version: '3.7'

services:
  caddy:
    image: "caddy:latest"
    restart: always
    volumes:
      - ./caddydata:/data  # to save certificates on disk
      - ./Caddyfile:/etc/caddy/Caddyfile  # to use the Caddyfile
      # - ./Caddyfile.prod:/etc/caddy/Caddyfile  # to use the Caddyfile
    ports:
      - 80:80
      - 443:443

  nginx:
    build: ./nginx
    expose:
      - 80
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - web

  web:
    build: ./
    # command: python manage.py runserver 0.0.0.0:8000
    # Gunicorn timeout: --timeout 300
    command: gunicorn --workers 10 --access-logfile - MSc_Research_Django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.prod.db

  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ./.env.prod.mq
    

volumes:
  postgres_data:
  static_volume:
  rabbitmq_volume: