# Generated by Django 2.2.6 on 2019-11-01 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='last_ready_signal',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 1, 0, 0)),
        ),
    ]
