# Generated by Django 2.2.6 on 2019-12-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_provider_last_ready_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='fabric_org',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
