# Generated by Django 2.2.6 on 2020-01-06 22:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_provider_fabric_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='last_ready_signal',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 1, 5, 18, tzinfo=utc)),
        ),
    ]
